### ISSUE TITLE
Emit CreateWarrior event when a new warrior is created.

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#1]
[Solidity Events](https://www.tutorialspoint.com/solidity/solidity_events.htm) store the arguments passed in the transaction logs when emitted. Events notify the applications about the change made to the contracts and applications which can be used to execute the dependent logic.

In `WarriorBase.sol`, we are creating a new warrior in `_createWarrior()`, now define an Event with appropriate data members, that is emitted when a new warrior is created.

**Comment by 0Rituraj01** [comment]
hey, i want to work on this issue

**Comment by schandu-eng** [comment]
I want to claim this issue

**Comment by sggts04** [comment]
@0Rituraj01 go ahead.

**Comment by sggts04** [comment]
@schandu-eng Go ahead.

**Comment by vaibhavsahu342** [comment]
Hey I want to work on this. Assign this issue to me

**Comment by batflarrow** [comment]
Since the two days are up... claim

**Comment by prakhar011** [comment]
claim

**Comment by sggts04** [comment]
@schandu-eng made the PR before the issue was un-assigned, and technically PRs have review-refactor time for 1 day. So this issue will only be unassigned if he fails to make a valid submission by tonight.
