### ISSUE TITLE
Rewrite DNA randomization logic

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#14]
The DNA has 10 digits, so it can be used to represent 5 stats with 2 digits each, so each stat can have the range `00-99`

These stats can be Attack, Defense, Speed, etc.. (You have to decide on the 5, comment your proposal before writing the code)

You then have to decide on the stat levels for different warriors, for example Elephants while have faster speed than a Swordsman, while the Knight can do more damage than the Archer. 

Now you have to write the code to randomize these stats according to the levels. (Elephants have fast speed so the random number generation should be only done at a higher range of numbers)

Also make sure to keep these numbers a little low because these will only be base stats and these stats will get increased as the the warrior gains xp and levels up to its new state.

**Comment by Monik09** [comment]
Claim

**Comment by sggts04** [comment]
Also, hope these 1,2,3,4 numbers are just relative terms. The initial stats will be then randomized using this relation.

**Comment by Monik09** [comment]
> Also, hope these 1,2,3,4 numbers are just relative terms. The initial stats will be then randomized using this relation.

Yeah they are relative terms.

**Comment by Monik09** [comment]
@sggts04 if this looks good now?
