### ISSUE TITLE
Shift the initialization of charactersticsMap to constructor

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#19]
Right now, the `charactersticsMap` is initialized with the same values every time random DNA has to be generated. This is bad practice in general and especially for Ethereum because it would cost a lot of gas.

Create a `constructor` and make this initialization there instead. And since `_generateRandomDna` won't do any state mutability anymore, you can turn that into a `view` function.

**Comment by criticic** [comment]
Claim
