### ISSUE TITLE
Generate a random DNA for Warrior with name and warriorType as seeds

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#2]
For our game, the DNA will decide the abilities and properties of a warrior and this DNA is randomly generated.

DNA will be a integer of length 10, generated randomly, each digit representing their abilities.

In `WarriorBase.sol`, complete the `_generateRandomDna()` function to generate a unit of length 10.

**Use the `dnaModulus` variable, and `_name` and `_warriorType` should act as seed for the random generator**. You'll have to use `abi.encodePacked()`, you can take inspiration from the CryptoZombies tutorial, they have implemented a similar random generator.

**Comment by sggts04** [comment]
@criticic go ahead.

**Comment by Abhijeet452** [comment]
Claim
