### ISSUE TITLE
Add public function to give player a random Item

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#27]
Create a public function `getDailyItem` which adds a random item to the player's inventory.

Solve this after #26 is solved, you can just generate a random `itemType` (between the range `0` and `4`), `name` can be anything for now, keep `itemLevel` as `1`.

**Comment by diyawaghmare** [comment]
claim

**Comment by medhatiwari** [comment]
Claim

**Comment by hotblooded058** [comment]
@sggts04 sir could please update me with the status #26 issue so I could procced further with mine issue #27

**Comment by sggts04** [comment]
Okay, you have time till midnight

**Comment by rushilpatra** [comment]
Can I get this issue?
