### ISSUE TITLE
Create an itemsMap which defines all items in the game.

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#28]
Create an `itemsMap` which defines all items in the game.

### Items
| itemType | name |
| ---- | ---- |
| 0 | Strength Potion |
| 1 | Haste Potion |
| 2 | Resistance Potion |
| 3 | Fitness Potion |
| 4 | Rapid Fire Potion |

itemsMap should be declared globally and initialized in the constructor.

**Comment by karankc23** [comment]
Claim
