### ISSUE TITLE
Assign correct item name and pass new Item directly to push() in getDailyItem()

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#33]
In `getDailyItem()`, write now a static name is being assigned to the random item, however we have now defined `itemsMap` which assigns name to each item Id, use that instead.

Also, in `getDailyItem()`, instead of creating an Item object in memory and then passing it to push(), create the object directly while passing it to push(). If confused, you can look at how `_createWarrior` is doing it.

**Comment by rushilpatra** [comment]
Claim

**Comment by sggts04** [comment]
@medhatiwari go ahead
