### ISSUE TITLE
Define the 4 warrior types.

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#4]
We now need to define the 4 types of warriors that a player can select from. Use your imagination and search up cool warrior types to select 4 names.

1. Add the 4 warrior types in a list in the readme.
2. In `WarriorBase.sol`, define a private view function `_returnWarriorType()` which takes in the warrior type id (0 - 3) and returns the name of the warrior type.

**Comment by sggts04** [comment]
@criticic go ahead.

**Comment by criticic** [comment]
Giant
- High Defense/HP
- Medium Attack (short-range)
- Low Speed

Barbarian
- High Attack (short range)
- Medium Speed
- Low Defense/HP

@sggts04 what do you think of these two?
also can you  discussion label to get feedback from others?

**Comment by sggts04** [comment]
@criticic these look okay, although I was thinking more along the lines of something like - Samurais, Ninjas, etc would feel cooler.

We can also go into the history books and pick something from there, something like - Mongols, Spartans, etc.

Giant, Barbarian just felt a little generic/common.

**Comment by criticic** [comment]
Archer
- High Accuracy
- Medium Attack
- Low Defense/HP

Yeah the names will be changed, btw how many stats should there be? with three there can be 6 permutations.

**Comment by criticic** [comment]
i found a few names: https://www.gameaboo.com/standard-rpg-classes-characters/

**Comment by criticic** [comment]
some names from Sword Art Online: https://aminoapps.com/c/sao__swordartonline/page/blog/sao-classes-and-subclasses/42Kg_aRKuYuoLdEVp6rbYoWkbrVm4D2jWdk
4 classes & 16 subclasses

**Comment by sggts04** [comment]
The DNA is defining the warrior stats. Since we chose a DNA of length 10, we can go for 5 stats so 2 digits can be used to denote each. We'll use actual numbers from 00-99 as stat detail instead of just high-low combinations, but the high-low will be used to assign a range for random stat generation in our DNA logic that we'll revisit.

**Comment by sggts04** [comment]
Also, big fan of Age of Empire 2, you can look into names from here too: https://ageofempires.fandom.com/wiki/Units_(Age_of_Empires_II)

**Comment by criticic** [comment]
- (00) Battle Elephant → (10) Elite battle elephant → (20) Destroyer Elephant
- (01) Knight → (11) Cavalier  → (21) Paladin
- (02) Archer → (22) Crossbowman  → (22) Arbalester
- (04) Long Swordsman → (14) Twohanded → (24) Champion

What do you think?

**Comment by sggts04** [comment]
Yea this seems great, go ahead. @criticic
