### ISSUE TITLE
Add an xp attribute to Warrior and create a public function to increase xp

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#5]
Our Warriors game will require daily efforts from the player to make their warrior strong, they'll have to train their warrior everyday to increase its `xp`.

1. Add a new attribute `xp` to the Warrior struct, and it will be initialized to 0 when a new warrior is created.
2. Create a public function `trainWarrior()` which increases the `xp` of a warrior by 100. Take in appropriate arguments and use `require()` method to check important conditions before training.

**Comment by batflarrow** [comment]
claim

**Comment by sggts04** [comment]
@batflarrow go ahead.
