### ISSUE TITLE
Emit WarriorTrained event when a warrior is trained.

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Warriors#9]
[Solidity Events](https://www.tutorialspoint.com/solidity/solidity_events.htm) store the arguments passed in the transaction logs when emitted. Events notify the applications about the change made to the contracts and applications which can be used to execute the dependent logic.

In `WarriorBase.sol`, we are training a warrior in `trainWarrior()`, now define a `WarriorTrained` Event with appropriate data members, that is emitted whenever a warrior is trained.

**Comment by batflarrow** [comment]
claim

**Comment by sggts04** [comment]
@batflarrow go ahead.
